### ISSUE TITLE
Mod isn't loading

### ISSUE THREAD

**Issue by anoomolu** [lukasabbe/DripFaster#1]
Hiya!

I installed Drip Faster the other day and it seemed to work fine, but when I ran my 1.20.1 pack with the mod included today, it seems to just not load for some reason. 

Here's my log: https://mclo.gs/Tw2pIZS
Comparing the modlist to loaded mods, Drip Faster doesn't show up.

Just a note, I think you've accidentally swapped the values for lava and water dripping, at least when looking at the wiki ^^

**Comment by lukasabbe** [comment]
That is very strange, i will test a few things and return here

Yes, I see that I have swapped the values for lava and water, thanks for pointing it out. Will fix

**Comment by lukasabbe** [comment]
This is now fixed, new versions on github

**Comment by anoomolu** [comment]
Thanks for the quick fix!
